### ISSUE TITLE
Support for join-ad-interest-group and run-ad-auction

### ISSUE THREAD

**Issue by violuke** [adamchainz/django-permissions-policy#405]
### Description

Chrome has started inserting an iframe on our website (in varying locations in the code) and sometimes this goes into a place that causes problems.

We've found [this guide](https://developer.chrome.com/docs/privacy-sandbox/protected-audience-api/opt-out/) that suggests that we can disable this feature using a Permissions Policy, but this excellent-looking project rejects this with an `ImproperlyConfigured` exception.

Would it be possible to add support for these?

Cheers!

**Comment by adamchainz** [comment]
My quarterly reminder to update feature lists came on Sep 20 but I didn't action it until now. Added in #406 and released in 4.18.0.

**Comment by violuke** [comment]
Wow, that's incredible. Thank you!
